removePathAccents = true
buildFuture = true
paginatePath = "page"
disableKinds = ["RSS", "section"]
pygmentsCodefences = true
copyright = "2022 by lernblog.org - Creative Commons Attribution-ShareAlike 4.0"

[params]
lernblogName = "Lernblog"
lernblogVersion = "1.5.1"
lernblogUrl = "https://www.lernblog.org"
paginateHome = 12
paginateTags = 36

[permalinks]
posts = "/:filename/"
pages = "/:filename/"

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "ATOM", "JSON"]
term = ["HTML", "ATOM"]

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.ATOM]
mediaType = "application/atom+xml"
baseName = "index"
isPlainText = false

[markup.goldmark.renderer]
unsafe= true