backend:
  name: git-gateway

media_folder: "content/media"
public_folder: "/media"

site_url: "/"
display_url: "https://lernblog.ch"

collections:
  - name: "posts"
    label: "Blogeinträge"
    label_singular: "Blogeintrag"
    description: >
      Hier können Blogeinträge verfasst, editiert und gelöscht werden.
      Blogeinträge erscheinen in der Übersicht auf der Frontseite.
    preview_path: "/"
    editor:
      preview: false
    folder: "content/posts"
    path: "{{slug}}/index"
    media_folder: "" # Stores media relative to content.
    public_folder: ""
    create: true
    format: "toml-frontmatter"
    fields:
      - {
          name: "title",
          label: "Titel",
          widget: "string",
          hint: "Beim ersten Speichern wird der Titel zur URL des Blogartikels.",
        }
      - {
          name: "date",
          label: "Datum",
          widget: "date",
          format: "YYYY-MM-DD",
          dateFormat: "DD.MM.YYYY",
        }
      - {
          name: "draft",
          label: "Entwurfsmodus",
          widget: "boolean",
          hint: "Einträge im Entwurfsmodus werden nicht angezeigt.",
          default: false,
        }
      - {
          name: "pinned",
          label: "Anheften",
          widget: "boolean",
          hint: "Angeheftete Einträge werden zuoberst vor den neusten Einträgen angezeigt.",
          default: false,
        }
      - {
          name: "tags",
          label: "Tags",
          widget: "list",
          required: false,
          pattern:
            [
              "^[^\\s#]+$",
              "Darf keine Leerschläge oder # enthalten. Mehrere Tags durch Komma trennen",
            ],
          hint: "Tags sind hilfreich, damit Besucher nach diesen filtern können. Mehrere Tags durch Komma trennen. Achtung: Darf keine Leerschläge oder # enthalten!",
        }
      - {
          name: "image",
          label: "Bild",
          widget: "image",
          required: false,
          hint: "Bild für Blogübersicht, Suchmaschinen und Social Media.",
          media_library: { config: { max_file_size: 256000 } },
        }
      - {
          name: "description",
          label: "Zusammenfassung",
          widget: "text",
          required: false,
          hint: "Kurze Beschreibung für Blogübersicht, Suchmaschinen und Social Media (ca. 2 Sätze).",
        }
      - {
          name: "body",
          label: "Inhalt",
          widget: "markdown",
          media_library: { config: { max_file_size: 512000 } },
        }
      - {
          name: "footnotes",
          label: "Fussnoten",
          widget: "markdown",
          minimal: true,
          buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list"],
          editorComponents: [],
          required: false,
          hint: "Kann für Quellenangaben oder andere Hinweise verwendet werden.",
        }
  - name: "pages"
    label: "Eigene Seiten"
    label_singular: "Seite"
    description: >
      Eigene Seiten erscheinen nicht in der Übersicht mit den Blogeinträgen auf der 
      Frontseite. Sie werden durch einen direkten Link aufgerufen. Wenn der Link unter 
      Einstellungen/Navigation hinzugefügt wird, dann ist die Seite über die 
      Navigation erreichbar.
    preview_path: "/"
    editor:
      preview: false
    folder: "content/pages"
    path: "{{slug}}/index"
    media_folder: "" # Stores media relative to content.
    public_folder: ""
    create: true
    format: "toml-frontmatter"
    fields:
      - {
          name: "title",
          label: "Titel",
          widget: "string",
          hint: "Beim ersten Speichern wird der Titel zur URL.",
        }
      - {
          name: "draft",
          label: "Entwurfsmodus",
          widget: "boolean",
          hint: "Seiten im Entwurfsmodus werden nicht angezeigt.",
          default: false,
        }
      - {
          name: "image",
          label: "Bild",
          widget: "image",
          required: false,
          hint: "Bild für Suchmaschinen und Social Media.",
          media_library: { config: { max_file_size: 256000 } },
        }
      - {
          name: "description",
          label: "Zusammenfassung",
          widget: "text",
          required: false,
          hint: "Kurze Beschreibung für Suchmaschinen und Social Media (ca. 2 Sätze).",
        }
      - {
          name: "body",
          label: "Inhalt",
          widget: "markdown",
          media_library: { config: { max_file_size: 512000 } },
        }
      - {
          name: "footnotes",
          label: "Fussnoten",
          widget: "markdown",
          minimal: true,
          buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list"],
          editorComponents: [],
          required: false,
          hint: "Kann für Quellenangaben oder andere Hinweise verwendet werden.",
        }
  - name: "settings"
    label: "Einstellungen"
    delete: false
    editor:
      preview: false
    format: "toml-frontmatter"
    files:
      - label: "Allgemein"
        name: "general"
        file: "content/settings/general/index.md"
        fields:
          - {
              name: "headless",
              label: "Headless",
              widget: "hidden",
              default: "true",
            }
          - {
              name: title,
              label: Seitentitel,
              widget: string,
              hint: "Haupttitel der Website.",
            }
          - {
              name: "description",
              label: "Beschreibung",
              widget: "string",
              hint: "Eine kurze Beschreibung der Website (Tagline).",
            }
          - {
              name: "footerLeft",
              label: "Fusszeile links",
              widget: "markdown",
              minimal: true,
              buttons:
                ["bold", "italic", "link", "bulleted-list", "numbered-list"],
              editorComponents: [],
              required: false,
              hint: "Fusszeile ganz unten links an der Seite.",
            }
          - {
              name: "footerRight",
              label: "Fusszeile rechts",
              widget: "markdown",
              minimal: true,
              buttons:
                ["bold", "italic", "link", "bulleted-list", "numbered-list"],
              editorComponents: [],
              required: false,
              hint: "Fusszeile ganz unten rechts an der Seite.",
            }
      - label: "Autor"
        name: "author"
        file: "content/settings/author/index.md"
        fields:
          - {
              label: "Headless",
              name: "headless",
              widget: "hidden",
              default: "true",
            }
          - {
              label: "Name des Autors",
              name: "name",
              widget: "string",
              hint: "Dein Vor- und Nachname.",
            }
          - {
              label: "Profilbild",
              name: "image",
              widget: "image",
              required: false,
              hint: "Kleines Bild (muss quadratisch sein).",
              media_library: { config: { max_file_size: 256000 } },
            }
          - {
              label: "E-Mail",
              name: "email",
              widget: "string",
              required: false,
              hint: "Deine E-Mail-Adresse. Diese wird verwendet, um dich als Autor erreichen zu können (z.B. für die Lernblog-Plattform).",
            }
      - name: "design"
        label: "Design"
        file: "content/settings/design/index.md"
        fields:
          - {
              label: "Headless",
              name: "headless",
              widget: "hidden",
              default: "true",
            }
          - {
              label: Icon,
              name: icon,
              widget: image,
              required: false,
              hint: "Kleines, quadratisches Bild für das Browser-Tab.",
              media_library: { config: { max_file_size: 256000 } },
            }
          - {
              label: Logo,
              name: logo,
              widget: image,
              required: false,
              hint: "Kleines Logo für die Navigation.",
              media_library: { config: { max_file_size: 256000 } },
            }
          - {
              label: Hauptbild,
              name: image,
              widget: image,
              required: false,
              hint: "Hintergrundbild für die Startseite.",
              media_library: { config: { max_file_size: 512000 } },
            }
          - {
              label: "Farbe",
              name: "color",
              widget: "string",
              required: false,
              hint: "Farbe für Links, Zitate, Buttons, etc. (als Hex-Farbcode, z.B. #ff7260)",
              pattern:
                ["^#[0-9a-fA-F]{3,6}$", "Muss ein gültiger Hex-Farbcode sein"],
            }
      - name: "navigation"
        label: "Navigation"
        file: "content/settings/navigation/index.md"
        fields:
          - {
              label: "Headless",
              name: "headless",
              widget: "hidden",
              default: "true",
            }
          - {
              label: "Link",
              name: "link",
              widget: "list",
              hint: "Links in der Navigation",
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: URL, name: url, widget: string },
                ],
            }
      - name: "code"
        label: "Code (für Profis)"
        file: "content/settings/code/index.md"
        fields:
          - {
              label: "Headless",
              name: "headless",
              widget: "hidden",
              default: "true",
            }
          - {
              label: Site Header Code,
              name: siteHeader,
              widget: text,
              required: false,
              hint: "Dieser Code wird im Head-Bereich auf jeder Seite eingefügt.",
            }
          - {
              label: Site Footer Code,
              name: siteFooter,
              widget: text,
              required: false,
              hint: "Dieser Code wird am Ende des Body-Bereichs auf jeder Seite eingefügt.",
            }
